fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
    serializer:
        serialize_null: true
    format_listener:
        rules:
            - { path: "^/", fallback_format: "json", priorities: ["json"] }
    param_fetcher_listener: force
    exception:
        enabled: true
        map_exception_codes: true
        codes: { App\Exception\ResourceValidationException: 400 }
        messages: { App\Exception\ResourceValidationException: true }
